### ISSUE TITLE
nx cloud integration not working

### ISSUE THREAD

**Issue by elvirdolic** [jdpearce/nx-azure-cloud#3]
Hello @jdpearce,

we have talked alredy on twitter. And I have tried your solution as well.

that's my token variable setting

![image](https://user-images.githubusercontent.com/17769458/79694197-27dd0b80-826f-11ea-96f9-57635edc2af2.png)

and in the yml I have following:

```
    - script: 'yarn affected:test --base=origin/master --head=HEAD --parallel --maxParallel=2'
      env: { NX_CLOUD_AUTH_TOKEN: $(NX_CLOUD_AUTH_TOKEN) }
```

but caching is not applied after a second run and I also can't see any trends in nx.app

![image](https://user-images.githubusercontent.com/17769458/79694234-5b1f9a80-826f-11ea-918c-ac808b7a5a26.png)

**Comment by elvirdolic** [comment]
The screenshot was cut off:

![image](https://user-images.githubusercontent.com/17769458/80076298-459ac100-854c-11ea-9ec1-934b9271ac2b.png)

**Comment by jdpearce** [comment]
@elvirdolic It looks to us like you've added an extra `=` to the end of the key, you may want to verify that you've added the right value to your variable.

**Comment by elvirdolic** [comment]
thank you very much. It works now
